on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Get all changed files excluding docs and README
      id: changed-files
      uses: tj-actions/changed-files@v46
      with:
        files_ignore: |
          **/*.md
          doc/*.{json,png,svg}

    - name: Run Revive Action by building from repository
      uses: morphy2k/revive-action@v2.7.4
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        exclude: "./vendor/..."
        name: "Revive"

    - name: Install kubebuilder tools
      if: steps.changed-files.outputs.any_changed == 'true'
      run: ./hack/install-kubebuilder-tools.sh

    - name: Generate code
      if: steps.changed-files.outputs.any_changed == 'true'
      run: ./hack/generate-code.sh && hack/verify-codegen.sh

    - name: Run go fmt
      if: steps.changed-files.outputs.any_changed == 'true'
      run: go fmt ./...
      #run: diff -u <(echo -n) <(gofmt -d -s .)

    - name: Run go vet
      if: steps.changed-files.outputs.any_changed == 'true'
      run: go vet --tags=test ./...

    - name: Install static check
      if: steps.changed-files.outputs.any_changed == 'true'
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Test
      if: steps.changed-files.outputs.any_changed == 'true'
      run: sudo PATH=${PATH}:./bin ./hack/test-go.sh

    - name: Send coverage
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out
        flag-name: Go-${{ matrix.go }}
      env:
        KUBEBUILDER_ASSETS: "$(pwd)/bin"

  e2e-test:
    name: e2e test
    runs-on: ubuntu-latest
    env:
      NUMBER_OF_COMPUTE_NODES: 5
      KIND_CLUSTER_NAME: whereabouts
      IMG_REGISTRY: ghcr.io/k8snetworkplumbingwg
      IMG_PROJECT: whereabouts
      IMG_TAG: latest
    steps:
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go version
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Get all changed files excluding docs and README
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files_ignore: |
            **/*.md
            doc/*.{json,png,svg}

      - name: Install requirements
        if: steps.changed-files.outputs.any_changed == 'true'
        run: sudo apt-get install nmap jq && ./hack/build-go.sh

      - name: Get test tools
        if: steps.changed-files.outputs.any_changed == 'true'
        run: source hack/e2e-get-test-tools.sh

      - name: Set up Kubernetes with Quick-K8s
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: palmsoftware/quick-k8s@v1
        with:
          clusterProvider: kind
          clusterName: ${{ env.KIND_CLUSTER_NAME }}
          numWorkerNodes: ${{ env.NUMBER_OF_COMPUTE_NODES }}
          installCalico: false
          waitForPodsReady: true

      - name: Install Multus CNI
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          MULTUS_DAEMONSET_URL="https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/deployments/multus-daemonset.yml"
          kubectl create -f "${MULTUS_DAEMONSET_URL}"
          kubectl -n kube-system wait --for=condition=ready -l name="multus" pod --timeout=300s

      - name: Install CNI plugins
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          kubectl create -f hack/cni-install.yml
          kubectl -n kube-system wait --for=condition=ready -l name="cni-plugins" pod --timeout=300s

      - name: Build and load whereabouts image
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          docker build . -t "$IMG_REGISTRY/$IMG_PROJECT:$IMG_TAG"
          docker save -o /tmp/whereabouts-img.tar "$IMG_REGISTRY/$IMG_PROJECT:$IMG_TAG"
          kind load image-archive --name "$KIND_CLUSTER_NAME" /tmp/whereabouts-img.tar
          rm /tmp/whereabouts-img.tar

      - name: Install whereabouts
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in "daemonset-install.yaml" "whereabouts.cni.cncf.io_ippools.yaml" "whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml" "whereabouts.cni.cncf.io_nodeslicepools.yaml"; do
            sed '/        image:/a\        imagePullPolicy: Never' "doc/crds/$file" | kubectl apply -f -
          done
          sed '/          image:/a\          imagePullPolicy: Never' "doc/crds/node-slice-controller.yaml" | kubectl apply -f -
          kubectl wait -n kube-system --for=condition=ready -l app=whereabouts pod --timeout=300s
          kubectl wait -n kube-system --for=condition=ready -l app=whereabouts-controller pod --timeout=300s

      - name: Clear test-cache
        if: steps.changed-files.outputs.any_changed == 'true'
        run: go clean -testcache

      - name: Execute golang based E2E tests
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          KUBECONFIG: /home/runner/.kube/config
          NUMBER_OF_THRASH_ITER: 20
          FILL_PERCENT_CAPACITY: 20
        run: pushd e2e; go test -v . -timeout 1h; popd
